name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        haxe: [latest, "2024-11-27_development_2dc801f"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}

    - name: Install dependencies
      run: |
        npm ci
        haxelib newrepo
        haxelib state load install.hxml

    - name: Check dependencies
      run: |
        haxe -version
        haxelib list

    - name: Build Haxe LSP
      run: haxe build.hxml

    - name: Run tests
      run: haxe test.hxml
